itemspath="C:\Users\bc-jo\IdeaProjects\coffee-shop\src\main\resources\items.csv"
customerpath="C:\Users\bc-jo\IdeaProjects\coffee-shop\src\main\resources\customers.csv"
orderpath="C:\Users\bc-jo\IdeaProjects\coffee-shop\src\main\resources\orders.csv"